# Generated by Django 2.1.7 on 2019-04-08 15:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryDesc', models.CharField(max_length=255)),
                ('parentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('colorID', models.AutoField(primary_key=True, serialize=False)),
                ('colorDesc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('camperID', models.IntegerField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('beginBalance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currentBalance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('endBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('donateBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('returnedBalance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('downloadBalance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemDesc', models.CharField(max_length=255)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorID', models.ManyToManyField(to='pos.Color')),
                ('itemID', models.ManyToManyField(to='pos.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.ManyToManyField(to='pos.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sizeID', models.AutoField(primary_key=True, serialize=False)),
                ('sizeDesc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('styleID', models.AutoField(primary_key=True, serialize=False)),
                ('styleDesc', models.CharField(max_length=255)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('transactionDate', models.DateTimeField(default=datetime.datetime.now)),
                ('transactionNotes', models.CharField(blank=True, max_length=255, null=True)),
                ('camperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Customer')),
                ('itemColor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Color')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Item')),
                ('itemSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.ItemSize')),
                ('submitUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemsize',
            name='sizeID',
            field=models.ManyToManyField(to='pos.Size'),
        ),
    ]
